[package]
name = "c0i"
version = "0.1.1"
authors = ["Lyzh <enterindex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "c0i"
path = "src/main.rs"


[lib]
name = "c0ilib"
path = "src/lib.rs"

[[example]]
name = "free_variables"
path = "examples/free_variables.rs"

[dependencies]
lazy_static = "^1.4.*"
sexpr_ir = { git="http://github.com/imlyzh/sexpr_ir" }
